package com.codeguard.backend.llm;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class LlmResponse {

    public enum FinishReason {
        STOP,
        LENGTH,
        TOOL_CALLS,
        CONTENT_FILTER,
        UNKNOWN
    }

    private String content;
    private String model;
    private FinishReason finishReason;

    // tokens send to the model
    private Integer promptTokens;

    // tokens generated by the model
    private Integer completionTokens;
}
