spring:
  config:
    import: optional:dotenv
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

security:
  encryption:
    key: ${ENCRYPTION_KEY}

llm:
  provider: groq

  groq:
    api-key: ${GROQ_API_KEY}
    model: llama-3.3-70b-versatile
    base-url: https://api.groq.com/openai/v1/chat/completions
